In [31]:
import tensorflow as tf
import numpy as np

In [32]:
size = 3
batch_size = 1
img_batch = np.arange(size*size*batch_size,dtype=np.float32)
img_batch = img_batch.reshape([batch_size,size,size,1]) #[batch_size, height, width, color]
img_batch.shape

(1, 3, 3, 1)

In [33]:
img_batch[0].T[0].T

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)

# convolution layer

In [34]:
filt =np.array([1.0]*(size*size*batch_size) ,dtype=np.float32)
filt = filt.reshape([size,size,1,1]) #[height, width, color, output_size]
filt.shape

(3, 3, 1, 1)

In [35]:
filt.T[0][0].T

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [36]:
h_conv = tf.nn.conv2d(img_batch, filt,strides=[1,1,1,1], padding='SAME' )

In [37]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    h = sess.run(h_conv)

In [49]:
h.shape

(1, 3, 3, 1)

In [39]:
h[0].T[0].T

array([[  8.,  15.,  12.],
       [ 21.,  36.,  27.],
       [ 20.,  33.,  24.]], dtype=float32)

In [40]:
#padding = SAME
[
[ 0.,  0.,  0., 0.,0.],
[ 0., 0.,  1.,  2.,0.],
[ 0., 3.,  4.,  5.,0.],
[ 0., 6.,  7.,  8.,0.],
[ 0., 0.,  0.,  0.,0.]
]

[[0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 2.0, 0.0],
 [0.0, 3.0, 4.0, 5.0, 0.0],
 [0.0, 6.0, 7.0, 8.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0]]

In [41]:
img_batch[0].T[0].T

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)

In [42]:
h[0].T[0].T   # bad filter

array([[  8.,  15.,  12.],
       [ 21.,  36.,  27.],
       [ 20.,  33.,  24.]], dtype=float32)

In [43]:
filt2 =np.array([1.0]*(size*size*batch_size) ,dtype=np.float32).reshape([size,size,1,1])

In [44]:
filt2.T[0][0].T[1][1]=100.0

In [55]:
filt2.T[0][0].T

(3, 3)

In [46]:
h_conv2 = tf.nn.conv2d(img_batch, filt2,strides=[1,1,1,1], padding='SAME' )

In [47]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    h2 = sess.run(h_conv2)

In [48]:
h2[0].T[0].T

array([[   8.,  114.,  210.],
       [ 318.,  432.,  522.],
       [ 614.,  726.,  816.]], dtype=float32)

# Pooling layer

In [62]:
img_batch[0].T[0].T

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)

In [67]:
h_pool = tf.nn.max_pool(img_batch, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

In [68]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    h_p = sess.run(h_pool)

In [69]:
h_p

array([[[[ 4.],
         [ 5.]],

        [[ 7.],
         [ 8.]]]], dtype=float32)

In [71]:
h_p[0].T[0].T

array([[ 4.,  5.],
       [ 7.,  8.]], dtype=float32)